spring:
  mvc:
    view:
      suffix: .jsp
      prefix:
  datasource:
    name: "DBPool"
    username: "root"
    password: "xy19990827"
    driver-class-name: "org.mariadb.jdbc.Driver"
    url: "jdbc:mariadb://127.0.0.1:3309/movieRecommder"

server:
  error:
    path: "/error"